apiVersion: polyfea.github.io/v1alpha1
kind: WebComponent
metadata:
  name: bm-ambulance-ufe-content
spec:
  microFrontend: bm-ambulance-ufe
  element: bm-ambulance-wl-app
  attributes:
    - name: base-path
      value: /bm-ambulance-wl/
  displayRules:
    - allOf:
      - context-name: main-content
      - path: "^(\\.?/)?bm-ambulance-wl(/.*)?$"