apiVersion: apps/v1
kind: Deployment
metadata:
  name: bm-ambulance-webapi
spec:
  template:
    spec:
      containers:
        - name: openapi-ui
          env:
            - name: URL
              value: /bm-openapi
            - name: BASE_URL
              value: /bm-openapi-ui